# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pf1524-ping

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_bf7d2b25cbf7486086fdf238b2b0027f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_62ff407c03824dbd8a514bf70e593ac0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bf7d2b25cbf7486086fdf238b2b0027f }}/ping:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pf1524-ping'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6c97f9f224424b58beb3d3044c59e643 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bf7d2b25cbf7486086fdf238b2b0027f }}/ping:${{ github.sha }}'